// Code generated by mockery. DO NOT EDIT.

package healthHandlers

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// MockInterfaceHealthHandler is an autogenerated mock type for the InterfaceHealthHandler type
type MockInterfaceHealthHandler struct {
	mock.Mock
}

// List provides a mock function with given fields:
func (_m *MockInterfaceHealthHandler) List() gin.HandlerFunc {
	ret := _m.Called()

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}
