// code generated by ifacemaker; DO NOT EDIT.

package healthHandlers

import (
	"github.com/gin-gonic/gin"
)

// InterfaceHealthHandler is the interface implemented by HealthHandler
type InterfaceHealthHandler interface {
	// List returns the health response
	List() gin.HandlerFunc
}
