// code generated by ifacemaker; DO NOT EDIT.

package dummyRepositories

import (
	"context"

	dummyModels "github.com/safciplak/microservice-starter/src/business/dummy/models"
	"github.com/safciplak/microservice-starter/src/models"
)

// InterfaceDummyRepository is the interface implemented by DummyRepository
type InterfaceDummyRepository interface {
	// List returns a slice of Dummy entities matching the given params
	List(ctx context.Context, params *dummyModels.QueryParams) ([]models.Dummy, error)
	// Read returns a single Dummy entity matching the params
	Read(ctx context.Context, params *dummyModels.QueryParams) (*models.Dummy, error)
	// Create creates a new Dummy entity
	Create(ctx context.Context, dummy *models.Dummy) error
	// Update updates a existing Dummy entity
	Update(ctx context.Context, dummy *models.Dummy) error
	// Delete (soft)deletes a existing Dummy entity
	Delete(ctx context.Context, dummy *models.Dummy) error
}
