// code generated by ifacemaker; DO NOT EDIT.

package dummyHandlers

import (
	"github.com/gin-gonic/gin"
)

// InterfaceDummyHandler is the interface implemented by DummyHandler
type InterfaceDummyHandler interface {
	// List returns a list of Dummy entities
	List() gin.HandlerFunc
	// Read returns a single Dummy entity
	Read() gin.HandlerFunc
	// Create creates a new Dummy entity
	Create() gin.HandlerFunc
	// Update updates a existing Dummy entity
	Update() gin.HandlerFunc
	// Delete (soft)deletes a existing Dummy entity
	Delete() gin.HandlerFunc
}
