// Code generated by mockery. DO NOT EDIT.

package providers

import mock "github.com/stretchr/testify/mock"

// MockInterfaceProviderService is an autogenerated mock type for the InterfaceProviderService type
type MockInterfaceProviderService struct {
	mock.Mock
}

// GetName provides a mock function with given fields:
func (_m *MockInterfaceProviderService) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Initialize provides a mock function with given fields:
func (_m *MockInterfaceProviderService) Initialize() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
