// code generated by ifacemaker; DO NOT EDIT.

package providers

// InterfaceProviderManager is the interface implemented by ProviderManager
type InterfaceProviderManager interface {
	// GetProvider returns the provider by the given name
	GetProvider(name string) (InterfaceProviderService, error)
}
