// Code generated by mockery. DO NOT EDIT.

package providers

import mock "github.com/stretchr/testify/mock"

// MockInterfaceProviderManager is an autogenerated mock type for the InterfaceProviderManager type
type MockInterfaceProviderManager struct {
	mock.Mock
}

// GetProvider provides a mock function with given fields: name
func (_m *MockInterfaceProviderManager) GetProvider(name string) (InterfaceProviderService, error) {
	ret := _m.Called(name)

	var r0 InterfaceProviderService
	if rf, ok := ret.Get(0).(func(string) InterfaceProviderService); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(InterfaceProviderService)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
