// Code generated by mockery. DO NOT EDIT.

package healthRepositories

import (
	context "context"

	models "github.com/safciplak/microservice-starter/src/models"
	mock "github.com/stretchr/testify/mock"
)

// MockInterfaceHealthRepository is an autogenerated mock type for the InterfaceHealthRepository type
type MockInterfaceHealthRepository struct {
	mock.Mock
}

// GetLastMigration provides a mock function with given fields: ctx
func (_m *MockInterfaceHealthRepository) GetLastMigration(ctx context.Context) (*models.SchemaMigrations, error) {
	ret := _m.Called(ctx)

	var r0 *models.SchemaMigrations
	if rf, ok := ret.Get(0).(func(context.Context) *models.SchemaMigrations); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SchemaMigrations)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
