// code generated by ifacemaker; DO NOT EDIT.

package healthRepositories

import (
	"context"

	"github.com/safciplak/microservice-starter/src/models"
)

// InterfaceHealthRepository is the interface implemented by HealthRepository
type InterfaceHealthRepository interface {
	// GetLastMigration gets the last migration
	GetLastMigration(ctx context.Context) (*models.SchemaMigrations, error)
}
