// code generated by ifacemaker; DO NOT EDIT.

package dummyServices

import (
	"context"

	dummyModels "github.com/safciplak/microservice-starter/src/business/dummy/models"
	"github.com/safciplak/microservice-starter/src/models"
)

// InterfaceDummyService is the interface implemented by DummyService
type InterfaceDummyService interface {
	// List returns a slice of Dummy entities matching the given params
	List(ctx context.Context, params *dummyModels.ListRequest) ([]models.Dummy, error)
	// Read returns a single Dummy entity matching the params
	Read(ctx context.Context, params *dummyModels.BaseRequest) (*models.Dummy, error)
	// Create creates a new Dummy entity
	Create(ctx context.Context, params *dummyModels.CreateRequest) (*models.Dummy, error)
	// Update updates a existing Dummy entity
	Update(ctx context.Context, params *dummyModels.UpdateRequest) (*models.Dummy, error)
	// Delete (soft)deletes a existing Dummy entity
	Delete(ctx context.Context, params *dummyModels.BaseRequest) (*models.Dummy, error)
}
