// code generated by ifacemaker; DO NOT EDIT.

package healthServices

import (
	"context"

	"github.com/safciplak/capila/src/http/response"
)

// InterfaceHealthService is the interface implemented by HealthService
type InterfaceHealthService interface {
	// Health returns the Health of the the microservice
	Health(ctx context.Context) *response.Response
}
