// Code generated by mockery. DO NOT EDIT.

package healthServices

import (
	context "context"

	response "github.com/safciplak/capila/src/http/response"
	mock "github.com/stretchr/testify/mock"
)

// MockInterfaceHealthService is an autogenerated mock type for the InterfaceHealthService type
type MockInterfaceHealthService struct {
	mock.Mock
}

// Health provides a mock function with given fields: ctx
func (_m *MockInterfaceHealthService) Health(ctx context.Context) *response.Response {
	ret := _m.Called(ctx)

	var r0 *response.Response
	if rf, ok := ret.Get(0).(func(context.Context) *response.Response); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.Response)
		}
	}

	return r0
}
